### ISSUE TITLE
QGuiApplication initial failed

### ISSUE THREAD

**Issue by ligongzheng** [LightZam/Qt-Library#1]
Hi:
    Thank you for your arm64 qt libraries firstly,I compiler the libraries successfully with your script. But I failed to run my application with a segment fault. The simple code : QGuiApplication a(argc,argv); cause this fault. My android API level is 21 and my device is meta 10.
   So I wonder do you have any idea about this ?
   Thank you in advance !
 best

**Comment by LightZam** [comment]
could you provide your error message?

and did you try use other arch with same code?

**Comment by ligongzheng** [comment]
No other error message was printed except the segmentation fault.  I must use arm86 arch so it's useless even if other arch would work. The point is that causing this problem is a very simple code which means the initialization of the qt . I doubt if the qt support arm64 or not.
