### ISSUE TITLE
qtdeclarative

### ISSUE THREAD

**Issue by manang** [LightZam/Qt-Library#2]
Hi,
why don't you include qtdeclarative in your build?
Thank you very much

Angelo

**Comment by LightZam** [comment]
no specific reason, i just skip source that useless to me

it can be added without any harm

**Comment by manang** [comment]
could you share a version with qtdeclarative?
thanks

**Comment by LightZam** [comment]
sure, i will do it in the weekend

**Comment by LightZam** [comment]
done, see 5.10.1
