### ISSUE TITLE
Could not find qmake configuration file android-g++.

### ISSUE THREAD

**Issue by manang** [LightZam/Qt-Library#3]
Hi,
thanks for the qtdeclarative qt environment.
I'm trying to build QtAV lib with the following istructions:
```
export ANDROID_NDK=${NDK}
export ANDROID_HOME=${SDK}
export ANDROID_NDK_HOST=${OS}-${ARCH}
export ANDROID_NDK_PLATFORM=android-26
export ANDROID_NDK_ROOT=${NDK}
export ANDROID_NDK_TOOLCHAIN_PREFIX=arm-linux-androideabi  
export ANDROID_NDK_TOOLCHAIN_VERSION=4.9
export ANDROID_NDK_TOOLS_PREFIX=arm-linux-androideabi  
export ANDROID_SDK_ROOT=${SDK} 
export ANDROID_API_VERSION=${ANDROID_PLATFORM}
export PATH=$PATH:${ANDROID_HOME}/tools:${JAVA_HOME}/bin
~/Qt-Library/5.10.1/android_arm64-v8a/bin/qmake -r -spec android-g++ ${DISTILLERY_ROOT_DIR}/qt/QtAV/QtAV.pro
```
But I have the following error:
Could not find qmake configuration file android-g++.
How Can I solve this issue?

p.s.
When I try to import the environment in Qt Creator I have the following message:
Qt version is not properly installed, please run make install.

Thanks

**Comment by LightZam** [comment]
did you follow the guide in README

```
Change Qt Library location by qt.conf
Add qt.conf to Qt/android_arm64-v8a/bin/qt.conf
You will be allowed to move library everywhere since you put this file.
[Paths]
Prefix: {the path you want}
```

**Comment by manang** [comment]
Ok,
the error was about qt.conf.
Thank you
Angelo

**Comment by manang** [comment]
I'm trying to compile an example.
I have a lot of errors. I want to know if the version of ndk is a problem to use this environment.
Thank you very much
Angelo

**Comment by LightZam** [comment]
According to Qt there is bug without android r10e version

your information was not enough to figure it out.

provide compile error log, please
